name: Publish docker image

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Restore and build
        run: |
          dotnet restore
          dotnet build

      - name: Build Docker image
        run: docker build -t sodensys/personnummergrupp5